### ISSUE TITLE
[master] device-virtual can't find device profiles, then crashes

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-virtual-go#98]
While debugging kuiper in the snap, I wanted to poke at the kuiper docker deployment, so I started up the nightly build (docker-compose-nexus-redis-no-secty.yml).

When device-virtual finally starts, it logs the following errors when trying to read device profiles from core-metadata:

```

edgex-device-virtual | level=INFO ts=22:02:20 app=device-virtual source=service.go:80 msg="Device Service device-virtual doesn't exist, creating a new one"
edgex-core-metadata  | level=ERROR ts=22:02:20 app=edgex-core-metadata source=handler.go:47 msg="Item not found"
edgex-device-virtual | level=INFO ts=22:02:20 app=device-virtual source=service.go:137 msg="Addressable device-virtual doesn't exist, creating a new one"
edgex-device-virtual | level=INFO ts=22:02:20 app=device-virtual source=autodiscovery.go:19 msg="AutoDiscovery stopped: disabled by configuration"
edgex-device-virtual | level=ERROR ts=22:02:20 app=device-virtual source=profiles.go:162 msg="Error when getting configuration from Core Metadata: 404 - 404 page not found\n "
edgex-device-virtual | level=ERROR ts=22:02:20 app=device-virtual source=profiles.go:162 msg="Error when getting configuration from Core Metadata: 404 - 404 page not found\n "
edgex-device-virtual | level=ERROR ts=22:02:20 app=device-virtual source=profiles.go:162 msg="Error when getting configuration from Core Metadata: 404 - 404 page not found\n "
edgex-device-virtual | level=ERROR ts=22:02:20 app=device-virtual source=profiles.go:162 msg="Error when getting configuration from Core Metadata: 404 - 404 page not found\n "
edgex-device-virtual | level=ERROR ts=22:02:20 app=device-virtual source=profiles.go:162 msg="Error when getting configuration from Core Metadata: 404 - 404 page not found\n "
```
I also went ahead and followed the kuiper tutorial here:

https://github.com/emqx/kuiper/blob/master/docs/en_US/edgex/edgex_rule_engine_tutorial.md

which seemed to work, although I didn't see any results when I queried the mqtt broker like this (see the section **Monitor analysis result**):

`mosquitto_sub -h broker.emqx.io -t result
`
Same thing with the client command listed under the same section. I went back to check the docker console output again, and I noticed that device-service-virtual had actually crashed:

```
edgex-device-virtual | level=INFO app=device-virtual source=device.go:52 msg="Added device 78ef4914-740e-4329-9633-5984e97b444e"
edgex-device-virtual | 2020/04/21 22:02:20 http: panic serving 172.21.0.8:60370: runtime error: invalid memory address or nil pointer dereference
edgex-device-virtual | goroutine 449 [running]:
edgex-device-virtual | net/http.(*conn).serve.func1(0xc00050c000)
edgex-device-virtual | 	/usr/local/go/src/net/http/server.go:1767 +0x139
edgex-device-virtual | panic(0x9aea40, 0xeb2250)
edgex-device-virtual | 	/usr/local/go/src/runtime/panic.go:679 +0x1b2
edgex-device-virtual | github.com/edgexfoundry/device-sdk-go/internal/autoevent.(*manager).StopForDevice(0x0, 0xc0000aa820, 0x15)
edgex-device-virtual | 	/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v1.2.0-dev.27/internal/autoevent/manager.go:94 +0x43
edgex-device-virtual | github.com/edgexfoundry/device-sdk-go/internal/autoevent.(*manager).RestartForDevice(0x0, 0xc0000aa820, 0x15)
edgex-device-virtual | 	/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v1.2.0-dev.27/internal/autoevent/manager.go:79 +0x5d
edgex-device-virtual | github.com/edgexfoundry/device-sdk-go/internal/handler/callback.handleDevice(0xc00050a040, 0x4, 0xc0000262a0, 0x24, 0x9a5940, 0xc0001f6080)
edgex-device-virtual | 	/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v1.2.0-dev.27/internal/handler/callback/device.go:69 +0x193c
edgex-device-virtual | github.com/edgexfoundry/device-sdk-go/internal/handler/callback.CallbackHandler(0xc0001e84c8, 0x6, 0xc0000262a0, 0x24, 0xc00050a040, 0x4, 0x10, 0xc0002c2878)
edgex-device-virtual | 	/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v1.2.0-dev.27/internal/handler/callback/general.go:25 +0x3af
edgex-device-virtual | github.com/edgexfoundry/device-sdk-go/internal/controller.callbackFunc(0xb39880, 0xc0000d41c0, 0xc0003e4b00)
edgex-device-virtual | 	/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v1.2.0-dev.27/internal/controller/restfuncs.go:101 +0x2cd
edgex-device-virtual | net/http.HandlerFunc.ServeHTTP(0xa858c0, 0xb39880, 0xc0000d41c0, 0xc0003e4b00)
edgex-device-virtual | 	/usr/local/go/src/net/http/server.go:2007 +0x44
edgex-device-virtual | github.com/edgexfoundry/device-sdk-go/internal/controller/correlation.OnRequestBegin.func1(0xb39880, 0xc0000d41c0, 0xc0003e4b00)
edgex-device-virtual | 	/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v1.2.0-dev.27/internal/controller/correlation/middleware.go:48 +0xdd
edgex-device-virtual | net/http.HandlerFunc.ServeHTTP(0xc0001f6020, 0xb39880, 0xc0000d41c0, 0xc0003e4b00)
edgex-device-virtual | 	/usr/local/go/src/net/http/server.go:2007 +0x44
edgex-device-virtual | github.com/edgexfoundry/device-sdk-go/internal/controller/correlation.OnResponseComplete.func1(0xb39880, 0xc0000d41c0, 0xc0003e4b00)
edgex-device-virtual | 	/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v1.2.0-dev.27/internal/controller/correlation/middleware.go:34 +0xa1
edgex-device-virtual | net/http.HandlerFunc.ServeHTTP(0xc0001f6040, 0xb39880, 0xc0000d41c0, 0xc0003e4b00)
edgex-device-virtual | 	/usr/local/go/src/net/http/server.go:2007 +0x44
edgex-device-virtual | github.com/edgexfoundry/device-sdk-go/internal/controller/correlation.ManageHeader.func1(0xb39880, 0xc0000d41c0, 0xc0003e4a00)
edgex-device-virtual | 	/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v1.2.0-dev.27/internal/controller/correlation/middleware.go:27 +0x1e7
edgex-device-virtual | net/http.HandlerFunc.ServeHTTP(0xc0001f6060, 0xb39880, 0xc0000d41c0, 0xc0003e4a00)
edgex-device-virtual | 	/usr/local/go/src/net/http/server.go:2007 +0x44
edgex-device-virtual | github.com/gorilla/mux.(*Router).ServeHTTP(0xc000142540, 0xb39880, 0xc0000d41c0, 0xc0003e4500)
edgex-device-virtual | 	/go/pkg/mod/github.com/gorilla/mux@v1.7.1/mux.go:212 +0xe2
edgex-device-virtual | net/http.serverHandler.ServeHTTP(0xc0000d40e0, 0xb39880, 0xc0000d41c0, 0xc0003e4500)
edgex-device-virtual | 	/usr/local/go/src/net/http/server.go:2802 +0xa4
edgex-device-virtual | net/http.(*conn).serve(0xc00050c000, 0xb3af80, 0xc00013a100)
edgex-device-virtual | 	/usr/local/go/src/net/http/server.go:1890 +0x875
edgex-device-virtual | created by net/http.(*Server).Serve
edgex-device-virtual | 	/usr/local/go/src/net/http/server.go:2928 +0x384



```

**Comment by cloudxxx8** [comment]
this issue might belong to SDK

**Comment by hahattan** [comment]
I've upgraded to the latest SDK which should resolve this issue, please pull the master branch and help verify if it's resolved @tonyespy

**Comment by tonyespy** [comment]
It still fails in the snap (built from master):

```
level=INFO ts=2020-04-22T13:54:52.321229805Z app=device-virtual source=config.go:321 msg="Configuration has been pushed to into Configuration Provider (1 environment overrides applied)"
level=ERROR ts=2020-04-22T13:54:52.321276952Z app=device-virtual source=logger.go:74 msg="logTarget cannot be blank, using stdout only"
level=INFO ts=2020-04-22T13:54:52.321299047Z app=device-virtual source=registry.go:79 msg="Using Registry (consul) from http://localhost:8500"
level=INFO ts=2020-04-22T13:54:52.322869881Z app=device-virtual source=config.go:308 msg="Writeable configuration has been updated from the Configuration Provider"
    2020/04/22 09:54:52 [INFO] agent: Synced service "device-virtual"
    2020/04/22 09:54:52 [INFO] agent: Synced check "Health Check: device-virtual"
level=INFO ts=2020-04-22T13:54:52.32653713Z app=device-virtual source=httpserver.go:89 msg="Web server starting (localhost:49990)"
level=INFO ts=2020-04-22T13:54:52.330651331Z app=device-virtual source=init.go:134 msg="Check Data service's status via Registry..."
level=INFO ts=2020-04-22T13:54:52.330651326Z app=device-virtual source=init.go:134 msg="Check Metadata service's status via Registry..."
level=INFO ts=2020-04-22T13:54:52.335242649Z app=device-virtual source=init.go:42 msg="Service clients initialize successful."
level=ERROR ts=2020-04-22T13:54:52.360519333Z app=edgex-core-metadata source=handler.go:47 msg="no item found for supplied key: device-virtual"
level=INFO ts=2020-04-22T13:54:52.360807914Z app=device-virtual source=service.go:83 msg="Device Service device-virtual doesn't exist, creating a new one"
level=INFO ts=2020-04-22T13:54:52.361266917Z app=device-virtual source=service.go:140 msg="Addressable device-virtual doesn't exist, creating a new one"
level=ERROR ts=2020-04-22T13:54:52.42890141Z app=device-virtual source=devices.go:43 msg="Device Profile Random-Binary-Device doesn't exist for Device Random-Binary-Device"
level=ERROR ts=2020-04-22T13:54:52.428946752Z app=device-virtual source=devices.go:31 msg="creating Device from config failed: Random-Binary-Device"

```
I'll give it a try with docker next...

**Comment by tonyespy** [comment]
@cloudxxx8 

I can't really validate this in docker-compose due to another bug in master preventing most of the core-* services from starting.

That said, device-virtual crashed after it's dependency timeout expired:

```
edgex-device-virtual      | level=ERROR ts=2020-04-22T14:17:26.680476335Z app=device-virtual source=init.go:112 msg="service dependency Data checking time out"
edgex-device-virtual      | level=ERROR ts=2020-04-22T14:17:26.680608923Z app=device-virtual source=init.go:112 msg="service dependency Metadata checking time out"
edgex-device-virtual      | error: checking required dependencied services failed 
edgex-device-virtual      | level=INFO ts=2020-04-22T14:17:26.681607372Z app=device-virtual source=httpserver.go:106 msg="Web server shutting down"
edgex-device-virtual      | level=INFO ts=2020-04-22T14:17:26.681744342Z app=device-virtual source=httpserver.go:108 msg="Web server shut down"
edgex-device-virtual      | level=INFO ts=2020-04-22T14:17:26.681768315Z app=device-virtual source=httpserver.go:97 msg="Web server stopped"
edgex-device-virtual      | level=INFO ts=2020-04-22T14:17:26.681834808Z app=device-virtual source=bootstrap.go:130 msg="Un-Registering service from the Registry"
edgex-core-consul         |     2020-04-22T14:17:26.685Z [INFO]  agent: Deregistered service: service=device-virtual
edgex-device-virtual      | panic: runtime error: invalid memory address or nil pointer dereference
edgex-device-virtual      | [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x92e2d9]
edgex-device-virtual      | 
edgex-device-virtual      | goroutine 1 [running]:
edgex-device-virtual      | github.com/edgexfoundry/device-virtual-go/internal/driver.(*VirtualDriver).Stop(0xc0000945f0, 0xc000111f00, 0x1, 0xc0001328f0)
edgex-device-virtual      | 	/go/src/github.com/edgexfoundry/device-virtual-go/internal/driver/virtualdriver.go:156 +0x29
edgex-device-virtual      | github.com/edgexfoundry/device-sdk-go/pkg/service.(*Service).Stop(0xc000220a00, 0xc000115000)
edgex-device-virtual      | 	/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v1.2.0-dev.27/pkg/service/service.go:67 +0x3e
edgex-device-virtual      | github.com/edgexfoundry/device-sdk-go/pkg/service.Main(0xa5bb7b, 0xe, 0xb21d20, 0xb, 0xa02d60, 0xc0000945f0, 0xb3af80, 0xc000115080, 0xc0000e4fd0, 0xc00011c540, ...)
edgex-device-virtual      | 	/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v1.2.0-dev.27/pkg/service/main.go:81 +0x6f0
edgex-device-virtual      | github.com/edgexfoundry/device-sdk-go/pkg/startup.Bootstrap(0xa5bb7b, 0xe, 0xb21d20, 0xb, 0xa02d60, 0xc0000945f0)
edgex-device-virtual      | 	/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v1.2.0-dev.27/pkg/startup/bootstrap.go:19 +0x112
edgex-device-virtual      | main.main()
edgex-device-virtual      | 	/go/src/github.com/edgexfoundry/device-virtual-go/cmd/main.go:21 +0x6f

```
Someone should try and verify this scenario and open another issue if reproduced.

**Comment by cloudxxx8** [comment]
@tonyespy we tried it on IDE and it worked fine.  I will take a look again.

**Comment by cloudxxx8** [comment]
@tonyespy I tried docker .  It cannot be run, but the issue you mentioned here doesn't exist.  Could you please help confirm you upgrade to the latest image?
`docker-compose -f docker-compose-nexus-redis.yml up -d`

**Comment by tonyespy** [comment]
@cloudxxx8 Yes, the images are kind of busted, but if you start docker-compose-nexus-mongo.yml you'll see the same failures I saw...

**Comment by hahattan** [comment]
@tonyespy @cloudxxx8 
I was using `docker-compose-nexus-redis-no-secty.yml` and changed the device-virtual image to my own built image(just run `make docker` in device-virtual-go directory) and it works well

**Comment by cloudxxx8** [comment]
@tonyespy I use docker-compose-nexus-mongo.yml, and device-virtual shuts down cleanly.

> level=ERROR ts=2020-04-22T16:02:45.777597129Z app=device-virtual source=init.go:149 msg=" edgex-core-metadata service not healthy..."
> level=INFO ts=2020-04-22T16:02:50.778425252Z app=device-virtual source=init.go:134 msg="Check Metadata service's status via Registry..."
> level=INFO ts=2020-04-22T16:02:50.778778052Z app=device-virtual source=init.go:134 msg="Check Data service's status via Registry..."
> level=ERROR ts=2020-04-22T16:02:50.780929178Z app=device-virtual source=init.go:149 msg=" edgex-core-metadata service not healthy..."
> level=ERROR ts=2020-04-22T16:02:55.781235961Z app=device-virtual source=init.go:112 msg="service dependency Metadata checking time out"
> error: checking required dependencied services failed
> level=INFO ts=2020-04-22T16:02:55.781567677Z app=device-virtual source=httpserver.go:106 msg="Web server shutting down"
> level=INFO ts=2020-04-22T16:02:55.781763716Z app=device-virtual source=httpserver.go:108 msg="Web server shut down"
> level=INFO ts=2020-04-22T16:02:55.781780484Z app=device-virtual source=httpserver.go:97 msg="Web server stopped"
> level=INFO ts=2020-04-22T16:02:55.781790484Z app=device-virtual source=bootstrap.go:130 msg="Un-Registering service from the Registry"

**Comment by cloudxxx8** [comment]
My image id is
nexus3.edgexfoundry.org:10004/docker-device-virtual-go                     master              9f0a134db7ad        7 hours ago         20.9MB

@tonyespy is it the same as yours
